apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-spring-demo
data:
  application.properties: |-
    spring.kafka.bootstrap-servers=${KAFKA_HOST}
    spring.sleuth.sampler.probability=1.0
    spring.zipkin.baseUrl=http://zipkin.istio-system:9411
    spring.zipkin.enabled=true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-spring-demo-deployment
spec:
  selector:
    matchLabels:
      app: kafka-spring-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-spring-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
        kiali.io/runtimes: springboot-tomcat,springboot-jvm,springboot-jvm-pool
    spec:
      containers:
        - name: kafka-spring-demo
          image: localhost.localdomain:5000/kafka-spring-demo:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: desenv
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-creds
                  key: bootstrap-servers

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-spring-demo
spec:
  selector:
    app: kafka-spring-demo
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
