apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-config-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: spring-config-reader
  apiGroup: rbac.authorization.k8s.io
